# Generated by Django 2.2.6 on 2019-10-29 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makepizza', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sauce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sauce', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='pizza',
            name='pizza_sauce',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='makepizza.Sauce'),
        ),
    ]
